; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27025.1 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG262277 DB	'c:\qt\5.12.3\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG262278 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG262279 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG262646 DB	'c:\qt\5.12.3\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG262647 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG262648 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_Gui@@3Uqt_meta_stringdata_Gui_t@@B DD 0ffffffffH ; qt_meta_stringdata_Gui
	DD	03H
	DD	00H
	ORG $+4
	DQ	0000000000000180H
	DD	0ffffffffH
	DD	015H
	DD	00H
	ORG $+4
	DQ	000000000000016cH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	000000000000016aH
	DD	0ffffffffH
	DD	011H
	DD	00H
	ORG $+4
	DQ	0000000000000153H
	DD	0ffffffffH
	DD	09H
	DD	00H
	ORG $+4
	DQ	000000000000014dH
	DD	0ffffffffH
	DD	0bH
	DD	00H
	ORG $+4
	DQ	000000000000013fH
	DD	0ffffffffH
	DD	09H
	DD	00H
	ORG $+4
	DQ	0000000000000133H
	DD	0ffffffffH
	DD	0aH
	DD	00H
	ORG $+4
	DQ	0000000000000125H
	DD	0ffffffffH
	DD	09H
	DD	00H
	ORG $+4
	DQ	0000000000000118H
	DD	0ffffffffH
	DD	04H
	DD	00H
	ORG $+4
	DQ	000000000000010aH
	DD	0ffffffffH
	DD	04H
	DD	00H
	ORG $+4
	DQ	00000000000000f7H
	DD	0ffffffffH
	DD	0cH
	DD	00H
	ORG $+4
	DQ	00000000000000e4H
	DD	0ffffffffH
	DD	0eH
	DD	00H
	ORG $+4
	DQ	00000000000000d9H
	DD	0ffffffffH
	DD	04H
	DD	00H
	ORG $+4
	DQ	00000000000000d0H
	DD	0ffffffffH
	DD	04H
	DD	00H
	ORG $+4
	DQ	00000000000000bdH
	DD	0ffffffffH
	DD	0aH
	DD	00H
	ORG $+4
	DQ	00000000000000aaH
	DB	047H
	DB	075H
	DB	069H
	DB	00H
	DB	063H
	DB	06fH
	DB	06eH
	DB	06eH
	DB	065H
	DB	063H
	DB	074H
	DB	053H
	DB	069H
	DB	067H
	DB	06eH
	DB	061H
	DB	06cH
	DB	041H
	DB	06eH
	DB	064H
	DB	053H
	DB	06cH
	DB	06fH
	DB	074H
	DB	073H
	DB	00H
	DB	00H
	DB	06dH
	DB	06fH
	DB	076H
	DB	065H
	DB	044H
	DB	06fH
	DB	067H
	DB	054H
	DB	06fH
	DB	041H
	DB	064H
	DB	06fH
	DB	070H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	00H
	DB	064H
	DB	065H
	DB	06cH
	DB	065H
	DB	074H
	DB	065H
	DB	044H
	DB	06fH
	DB	067H
	DB	00H
	DB	06dH
	DB	06fH
	DB	076H
	DB	065H
	DB	041H
	DB	06cH
	DB	06cH
	DB	044H
	DB	06fH
	DB	067H
	DB	073H
	DB	00H
	DB	061H
	DB	064H
	DB	064H
	DB	04eH
	DB	065H
	DB	077H
	DB	044H
	DB	06fH
	DB	067H
	DB	00H
	DB	066H
	DB	069H
	DB	06cH
	DB	074H
	DB	065H
	DB	072H
	DB	044H
	DB	06fH
	DB	067H
	DB	073H
	DB	00H
	DB	075H
	DB	070H
	DB	064H
	DB	061H
	DB	074H
	DB	065H
	DB	044H
	DB	06fH
	DB	067H
	DB	00H
	DB	06eH
	DB	065H
	DB	078H
	DB	074H
	DB	00H
	DB	06fH
	DB	070H
	DB	065H
	DB	06eH
	DB	00H
	DB	06fH
	DB	070H
	DB	065H
	DB	06eH
	DB	041H
	DB	064H
	DB	06fH
	DB	070H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	00H
	DB	069H
	DB	074H
	DB	065H
	DB	072H
	DB	061H
	DB	074H
	DB	065H
	DB	064H
	DB	046H
	DB	069H
	DB	06cH
	DB	074H
	DB	065H
	DB	072H
	DB	00H
	DB	075H
	DB	06eH
	DB	064H
	DB	06fH
	DB	00H
	DB	072H
	DB	065H
	DB	064H
	DB	06fH
	DB	00H
	DB	06eH
	DB	065H
	DB	077H
	DB	05fH
	DB	077H
	DB	069H
	DB	06eH
	DB	064H
	DB	06fH
	DB	077H
	DB	00H
	ORG $+3
?qt_meta_data_Gui@@3QBIB DD 08H				; qt_meta_data_Gui
	DD	00H
	DD	00H
	DD	00H
	DD	0eH
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	054H
	DD	02H
	DD	08H
	DD	03H
	DD	00H
	DD	055H
	DD	02H
	DD	08H
	DD	04H
	DD	00H
	DD	056H
	DD	02H
	DD	08H
	DD	05H
	DD	00H
	DD	057H
	DD	02H
	DD	08H
	DD	06H
	DD	00H
	DD	058H
	DD	02H
	DD	08H
	DD	07H
	DD	00H
	DD	059H
	DD	02H
	DD	08H
	DD	08H
	DD	00H
	DD	05aH
	DD	02H
	DD	08H
	DD	09H
	DD	00H
	DD	05bH
	DD	02H
	DD	08H
	DD	0aH
	DD	00H
	DD	05cH
	DD	02H
	DD	08H
	DD	0bH
	DD	00H
	DD	05dH
	DD	02H
	DD	08H
	DD	0cH
	DD	00H
	DD	05eH
	DD	02H
	DD	08H
	DD	0dH
	DD	00H
	DD	05fH
	DD	02H
	DD	08H
	DD	0eH
	DD	00H
	DD	060H
	DD	02H
	DD	08H
	DD	0fH
	DD	00H
	DD	061H
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	00H
	ORG $+4
$SG263015 DB	'c:\qt\5.12.3\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG263016 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG263017 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG263866 DB	'c:\qt\5.12.3\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG263867 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG263868 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG264235 DB	'c:\qt\5.12.3\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG264236 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG264237 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG264604 DB	'c:\qt\5.12.3\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG264605 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG264606 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG265022 DB	'c:\qt\5.12.3\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG265023 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG265024 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG258907 DB	'c:\qt\5.12.3\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG258908 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG258909 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@Gui@@UEBAPEBUQMetaObject@@XZ	; Gui::metaObject
PUBLIC	?qt_metacast@Gui@@UEAAPEAXPEBD@Z		; Gui::qt_metacast
PUBLIC	?qt_metacall@Gui@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; Gui::qt_metacall
PUBLIC	?qt_static_metacall@Gui@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; Gui::qt_static_metacall
PUBLIC	?staticMetaObject@Gui@@2UQMetaObject@@B		; Gui::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?connectSignalAndSlots@Gui@@AEAAXXZ:PROC	; Gui::connectSignalAndSlots
EXTRN	?moveDogToAdoption@Gui@@AEAAXXZ:PROC		; Gui::moveDogToAdoption
EXTRN	?deleteDog@Gui@@AEAAXXZ:PROC			; Gui::deleteDog
EXTRN	?moveAllDogs@Gui@@AEAAXXZ:PROC			; Gui::moveAllDogs
EXTRN	?addNewDog@Gui@@AEAAXXZ:PROC			; Gui::addNewDog
EXTRN	?filterDogs@Gui@@AEAAXXZ:PROC			; Gui::filterDogs
EXTRN	?updateDog@Gui@@AEAAXXZ:PROC			; Gui::updateDog
EXTRN	?next@Gui@@AEAAXXZ:PROC				; Gui::next
EXTRN	?open@Gui@@AEAAXXZ:PROC				; Gui::open
EXTRN	?openAdoption@Gui@@AEAAXXZ:PROC			; Gui::openAdoption
EXTRN	?iteratedFilter@Gui@@AEAAXXZ:PROC		; Gui::iteratedFilter
EXTRN	?undo@Gui@@AEAAXXZ:PROC				; Gui::undo
EXTRN	?redo@Gui@@AEAAXXZ:PROC				; Gui::redo
EXTRN	?new_window@Gui@@AEAAXXZ:PROC			; Gui::new_window
EXTRN	__imp_?staticMetaObject@QWidget@@2UQMetaObject@@B:BYTE
EXTRN	__ImageBase:BYTE
_BSS	SEGMENT
?staticMetaObject@Gui@@2UQMetaObject@@B DB 030H DUP (?)	; Gui::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@Gui@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@Gui@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@Gui@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@Gui@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@Gui@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@Gui@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@Gui@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN22
	DD	imagerel $LN22+324
	DD	imagerel $unwind$?qt_static_metacall@Gui@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@Gui@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@Gui@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@Gui@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@Gui@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@Gui@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@Gui@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@Gui@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@Gui@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@Gui@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'Gui::staticMetaObject'', COMDAT
; File c:\users\andreas-pc\source\repos\as11-12\as11-12\generatedfiles\debug\moc_gui.cpp
; Line 135
	mov	rax, QWORD PTR __imp_?staticMetaObject@QWidget@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@Gui@@2UQMetaObject@@B, rax
; Line 136
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_Gui@@3Uqt_meta_stringdata_Gui_t@@B
	mov	QWORD PTR ?staticMetaObject@Gui@@2UQMetaObject@@B+8, rax
; Line 137
	lea	rax, OFFSET FLAT:?qt_meta_data_Gui@@3QBIB
	mov	QWORD PTR ?staticMetaObject@Gui@@2UQMetaObject@@B+16, rax
; Line 138
	lea	rax, OFFSET FLAT:?qt_static_metacall@Gui@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; Gui::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@Gui@@2UQMetaObject@@B+24, rax
; Line 139
	mov	QWORD PTR ?staticMetaObject@Gui@@2UQMetaObject@@B+32, 0
; Line 140
	mov	QWORD PTR ?staticMetaObject@Gui@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@Gui@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'Gui::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@Gui@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; Gui::qt_static_metacall
; File c:\users\andreas-pc\source\repos\as11-12\as11-12\generatedfiles\debug\moc_gui.cpp
; Line 109
$LN22:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 110
	cmp	DWORD PTR _c$[rsp], 0
	jne	$LN4@qt_static_
; Line 111
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 113
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 13
	ja	$LN19@qt_static_
	movsxd	rax, DWORD PTR tv69[rsp]
	lea	rcx, OFFSET FLAT:__ImageBase
	mov	eax, DWORD PTR $LN21@qt_static_[rcx+rax*4]
	add	rax, rcx
	jmp	rax
$LN5@qt_static_:
; Line 114
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?connectSignalAndSlots@Gui@@AEAAXXZ	; Gui::connectSignalAndSlots
	jmp	$LN2@qt_static_
$LN6@qt_static_:
; Line 115
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?moveDogToAdoption@Gui@@AEAAXXZ		; Gui::moveDogToAdoption
	jmp	$LN2@qt_static_
$LN7@qt_static_:
; Line 116
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?deleteDog@Gui@@AEAAXXZ			; Gui::deleteDog
	jmp	$LN2@qt_static_
$LN8@qt_static_:
; Line 117
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?moveAllDogs@Gui@@AEAAXXZ		; Gui::moveAllDogs
	jmp	SHORT $LN2@qt_static_
$LN9@qt_static_:
; Line 118
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?addNewDog@Gui@@AEAAXXZ			; Gui::addNewDog
	jmp	SHORT $LN2@qt_static_
$LN10@qt_static_:
; Line 119
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?filterDogs@Gui@@AEAAXXZ		; Gui::filterDogs
	jmp	SHORT $LN2@qt_static_
$LN11@qt_static_:
; Line 120
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?updateDog@Gui@@AEAAXXZ			; Gui::updateDog
	jmp	SHORT $LN2@qt_static_
$LN12@qt_static_:
; Line 121
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?next@Gui@@AEAAXXZ			; Gui::next
	jmp	SHORT $LN2@qt_static_
$LN13@qt_static_:
; Line 122
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?open@Gui@@AEAAXXZ			; Gui::open
	jmp	SHORT $LN2@qt_static_
$LN14@qt_static_:
; Line 123
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?openAdoption@Gui@@AEAAXXZ		; Gui::openAdoption
	jmp	SHORT $LN2@qt_static_
$LN15@qt_static_:
; Line 124
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?iteratedFilter@Gui@@AEAAXXZ		; Gui::iteratedFilter
	jmp	SHORT $LN2@qt_static_
$LN16@qt_static_:
; Line 125
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?undo@Gui@@AEAAXXZ			; Gui::undo
	jmp	SHORT $LN2@qt_static_
$LN17@qt_static_:
; Line 126
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?redo@Gui@@AEAAXXZ			; Gui::redo
	jmp	SHORT $LN2@qt_static_
$LN18@qt_static_:
; Line 127
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?new_window@Gui@@AEAAXXZ		; Gui::new_window
$LN19@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 132
	add	rsp, 56					; 00000038H
	ret	0
	npad	1
$LN21@qt_static_:
	DD	$LN5@qt_static_
	DD	$LN6@qt_static_
	DD	$LN7@qt_static_
	DD	$LN8@qt_static_
	DD	$LN9@qt_static_
	DD	$LN10@qt_static_
	DD	$LN11@qt_static_
	DD	$LN12@qt_static_
	DD	$LN13@qt_static_
	DD	$LN14@qt_static_
	DD	$LN15@qt_static_
	DD	$LN16@qt_static_
	DD	$LN17@qt_static_
	DD	$LN18@qt_static_
?qt_static_metacall@Gui@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; Gui::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@Gui@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; Gui::qt_metacall
; File c:\users\andreas-pc\source\repos\as11-12\as11-12\generatedfiles\debug\moc_gui.cpp
; Line 158
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 159
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 160
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 161
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 162
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 163
	cmp	DWORD PTR _id$[rsp], 14
	jge	SHORT $LN5@qt_metacal
; Line 164
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@Gui@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; Gui::qt_static_metacall
$LN5@qt_metacal:
; Line 165
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 14
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 166
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 167
	cmp	DWORD PTR _id$[rsp], 14
	jge	SHORT $LN7@qt_metacal
; Line 168
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 169
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 14
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 171
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 172
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@Gui@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; Gui::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@Gui@@UEAAPEAXPEBD@Z PROC			; Gui::qt_metacast
; File c:\users\andreas-pc\source\repos\as11-12\as11-12\generatedfiles\debug\moc_gui.cpp
; Line 150
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 151
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 152
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_Gui@@3Uqt_meta_stringdata_Gui_t@@B+384
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 153
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 154
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 155
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@Gui@@UEAAPEAXPEBD@Z ENDP			; Gui::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@Gui@@UEBAPEBUQMetaObject@@XZ PROC		; Gui::metaObject
; File c:\users\andreas-pc\source\repos\as11-12\as11-12\generatedfiles\debug\moc_gui.cpp
; Line 145
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 146
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@Gui@@2UQMetaObject@@B ; Gui::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 147
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@Gui@@UEBAPEBUQMetaObject@@XZ ENDP		; Gui::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File c:\qt\5.12.3\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File c:\users\andreas-pc\source\repos\as11-12\as11-12\generatedfiles\debug\moc_gui.cpp
; Line 175
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File c:\users\andreas-pc\source\repos\as11-12\as11-12\generatedfiles\debug\moc_gui.cpp
; Line 175
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
